use anyhow::Context;

use crate::model::{BenchReport, MetricSnapshot};

const WIDTH: f64 = 1200.0;
const HEIGHT: f64 = 1600.0;
const WATERMARK: &str = "南京非迅科技";

#[derive(Clone, Copy, PartialEq, Eq)]
enum ExportLang {
    En,
    Zh,
}

impl ExportLang {
    fn parse(lang: &str) -> Self {
        if lang.to_ascii_lowercase().starts_with("zh") {
            Self::Zh
        } else {
            Self::En
        }
    }
}

struct ExportText {
    report_title: &'static str,
    specimen: &'static str,
    tags: &'static str,
    run: &'static str,
    mode: &'static str,
    status: &'static str,
    started: &'static str,
    no_specimen: &'static str,
    none: &'static str,
    duration: &'static str,
    samples: &'static str,
    max_conn: &'static str,
    published: &'static str,
    received: &'static str,
    errors: &'static str,
    avg_pub_rate: &'static str,
    avg_recv_rate: &'static str,
    max_pub_rate: &'static str,
    max_recv_rate: &'static str,
    latency_avg: &'static str,
    latency_p50: &'static str,
    latency_p90: &'static str,
    latency_p95: &'static str,
    latency_p99: &'static str,
    latency_p999: &'static str,
    latency_max: &'static str,
    throughput: &'static str,
    latency: &'static str,
    publish: &'static str,
    receive: &'static str,
    avg: &'static str,
    max: &'static str,
    generated: &'static str,
    watermark: &'static str,
    broker: &'static str,
    clients: &'static str,
    topic: &'static str,
}

impl ExportText {
    fn for_lang(lang: ExportLang) -> Self {
        match lang {
            ExportLang::En => Self {
                report_title: "VelaMQ Bench Report",
                specimen: "Specimen",
                tags: "Tags",
                run: "Run",
                mode: "Mode",
                status: "Status",
                started: "Started",
                no_specimen: "No specimen",
                none: "none",
                duration: "Duration",
                samples: "Samples",
                max_conn: "Max Conn",
                published: "Published",
                received: "Received",
                errors: "Errors",
                avg_pub_rate: "Avg Pub/s",
                avg_recv_rate: "Avg Recv/s",
                max_pub_rate: "Max Pub/s",
                max_recv_rate: "Max Recv/s",
                latency_avg: "Latency Avg",
                latency_p50: "Latency P50",
                latency_p90: "Latency P90",
                latency_p95: "Latency P95",
                latency_p99: "Latency P99",
                latency_p999: "Latency P99.9",
                latency_max: "Latency Max",
                throughput: "Throughput",
                latency: "Latency",
                publish: "publish",
                receive: "receive",
                avg: "avg",
                max: "max",
                generated: "Generated by velamq-bench",
                watermark: "Watermark",
                broker: "Broker",
                clients: "Clients",
                topic: "Topic",
            },
            ExportLang::Zh => Self {
                report_title: "VelaMQ Bench 压测报告",
                specimen: "标本",
                tags: "标签",
                run: "运行ID",
                mode: "模式",
                status: "状态",
                started: "开始时间",
                no_specimen: "无标本",
                none: "无",
                duration: "持续时间",
                samples: "采样点",
                max_conn: "最大连接",
                published: "发布总数",
                received: "接收总数",
                errors: "错误总数",
                avg_pub_rate: "平均发布/秒",
                avg_recv_rate: "平均接收/秒",
                max_pub_rate: "峰值发布/秒",
                max_recv_rate: "峰值接收/秒",
                latency_avg: "平均延迟",
                latency_p50: "P50 延迟",
                latency_p90: "P90 延迟",
                latency_p95: "P95 延迟",
                latency_p99: "P99 延迟",
                latency_p999: "P99.9 延迟",
                latency_max: "最大延迟",
                throughput: "吞吐量",
                latency: "延迟",
                publish: "发布",
                receive: "接收",
                avg: "平均",
                max: "最大",
                generated: "由 velamq-bench 生成",
                watermark: "水印",
                broker: "Broker",
                clients: "客户端",
                topic: "主题",
            },
        }
    }
}

pub fn report_to_svg(report: &BenchReport, lang: &str) -> String {
    let lang = ExportLang::parse(lang);
    let text = ExportText::for_lang(lang);
    let specimen_name = report
        .run
        .specimen
        .as_ref()
        .map(|specimen| specimen.name.as_str())
        .unwrap_or(text.no_specimen);
    let tags = report
        .run
        .specimen
        .as_ref()
        .map(|specimen| specimen.tags.join(", "))
        .filter(|tags| !tags.is_empty())
        .unwrap_or_else(|| text.none.to_string());

    let mut svg = String::new();
    svg.push_str(&format!(
        r##"<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}">
<defs>
  <style>
    .font {{ font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans CJK SC", Arial, sans-serif; }}
    .muted {{ fill: #65738a; }}
    .ink {{ fill: #1c2533; }}
  </style>
</defs>
<rect width="{WIDTH}" height="{HEIGHT}" fill="#f6f8fb"/>
<g class="font" opacity="0.08" fill="#2f6fed" font-size="92" font-weight="800" transform="rotate(-30 600 800)">
  <text x="80" y="300">{watermark}</text>
  <text x="360" y="620">{watermark}</text>
  <text x="120" y="960">{watermark}</text>
  <text x="460" y="1300">{watermark}</text>
</g>
"##,
        watermark = escape_xml(WATERMARK)
    ));

    svg.push_str(&format!(
        r#"<g class="font">
<text x="64" y="82" class="ink" font-size="38" font-weight="850">{title}</text>
<text x="64" y="122" class="muted" font-size="18">{specimen_label}: {specimen}</text>
<text x="64" y="152" class="muted" font-size="18">{tags_label}: {tags}</text>
<text x="64" y="182" class="muted" font-size="18">{run_label}: {run_id}</text>
<text x="760" y="122" class="muted" font-size="18">{mode_label}: {mode}</text>
<text x="760" y="152" class="muted" font-size="18">{status_label}: {status}</text>
<text x="760" y="182" class="muted" font-size="18">{started_label}: {started}</text>
</g>
"#,
        title = escape_xml(text.report_title),
        specimen_label = escape_xml(text.specimen),
        specimen = escape_xml(specimen_name),
        tags_label = escape_xml(text.tags),
        tags = escape_xml(&tags),
        run_label = escape_xml(text.run),
        run_id = escape_xml(&report.run.id),
        mode_label = escape_xml(text.mode),
        mode = escape_xml(&mode_label(&report.run.mode, lang)),
        status_label = escape_xml(text.status),
        status = escape_xml(&status_label(&report.run.status, lang)),
        started_label = escape_xml(text.started),
        started = escape_xml(&report.run.started_at.to_rfc3339())
    ));

    let cards = [
        (
            text.duration,
            format_duration(report.stats.duration_ms, lang),
        ),
        (text.samples, report.stats.sample_count.to_string()),
        (text.max_conn, report.stats.max_connected.to_string()),
        (text.published, compact(report.stats.total_published as f64)),
        (text.received, compact(report.stats.total_received as f64)),
        (text.errors, compact(report.stats.total_errors as f64)),
        (
            text.avg_pub_rate,
            format_rate(report.stats.avg_publish_rate),
        ),
        (
            text.avg_recv_rate,
            format_rate(report.stats.avg_receive_rate),
        ),
        (
            text.max_pub_rate,
            format_rate(report.stats.max_publish_rate),
        ),
        (
            text.max_recv_rate,
            format_rate(report.stats.max_receive_rate),
        ),
        (
            text.latency_avg,
            format_ms(report.stats.latency_avg_ms, lang),
        ),
        (
            text.latency_p50,
            format_ms(report.stats.latency_p50_ms, lang),
        ),
        (
            text.latency_p90,
            format_ms(report.stats.latency_p90_ms, lang),
        ),
        (
            text.latency_p95,
            format_ms(report.stats.latency_p95_ms, lang),
        ),
        (
            text.latency_p99,
            format_ms(report.stats.latency_p99_ms, lang),
        ),
        (
            text.latency_p999,
            format_ms(report.stats.latency_p999_ms, lang),
        ),
        (
            text.latency_max,
            format_ms(report.stats.latency_max_ms, lang),
        ),
    ];
    svg.push_str(&summary_cards(&cards, 64.0, 230.0));

    svg.push_str(&chart_svg(
        text.throughput,
        64.0,
        730.0,
        1072.0,
        300.0,
        &[
            ChartSeries::from_snapshots(text.publish, "#2f6fed", report, |s| s.publish_rate),
            ChartSeries::from_snapshots(text.receive, "#16845b", report, |s| s.receive_rate),
        ],
        AxisFormat::Rate,
        text.samples,
        lang,
    ));

    svg.push_str(&chart_svg(
        text.latency,
        64.0,
        1090.0,
        1072.0,
        320.0,
        &[
            ChartSeries::from_snapshots(text.avg, "#d97706", report, |s| s.latency_avg_ms),
            ChartSeries::from_snapshots(text.latency_p95, "#0ea5e9", report, |s| s.latency_p95_ms),
            ChartSeries::from_snapshots(text.latency_p99, "#ef4444", report, |s| s.latency_p99_ms),
            ChartSeries::from_snapshots(text.max, "#7c3aed", report, |s| s.latency_max_ms),
        ],
        AxisFormat::Millis,
        text.samples,
        lang,
    ));

    svg.push_str(&format!(
        r#"<g class="font">
<text x="64" y="1484" class="muted" font-size="16">{generated}. {watermark_label}: {watermark}</text>
<text x="64" y="1512" class="muted" font-size="16">{broker_label}: {host}:{port} · {clients_label}: {clients} · {topic_label}: {topic}</text>
</g>
</svg>"#,
        generated = escape_xml(text.generated),
        watermark_label = escape_xml(text.watermark),
        watermark = escape_xml(WATERMARK),
        broker_label = escape_xml(text.broker),
        host = escape_xml(&report.run.config.host),
        port = report.run.config.port,
        clients_label = escape_xml(text.clients),
        clients = report.run.config.clients,
        topic_label = escape_xml(text.topic),
        topic = escape_xml(&report.run.config.topic)
    ));

    svg
}

pub fn report_to_pdf(report: &BenchReport, lang: &str) -> anyhow::Result<Vec<u8>> {
    let svg = report_to_svg(report, lang);
    let mut options = svg2pdf::usvg::Options::default();
    options.fontdb_mut().load_system_fonts();
    let tree = svg2pdf::usvg::Tree::from_str(&svg, &options)
        .context("failed to parse report svg for pdf export")?;
    let pdf = svg2pdf::to_pdf(
        &tree,
        svg2pdf::ConversionOptions {
            embed_text: false,
            ..svg2pdf::ConversionOptions::default()
        },
        svg2pdf::PageOptions::default(),
    )
    .map_err(|err| anyhow::anyhow!("failed to convert report svg to pdf: {err}"))?;
    Ok(pdf)
}

struct ChartSeries {
    label: &'static str,
    color: &'static str,
    points: Vec<ChartPoint>,
}

struct ChartPoint {
    elapsed_secs: f64,
    value: f64,
}

impl ChartSeries {
    fn from_snapshots(
        label: &'static str,
        color: &'static str,
        report: &BenchReport,
        mapper: impl Fn(&MetricSnapshot) -> f64,
    ) -> Self {
        Self {
            label,
            color,
            points: report
                .snapshots
                .iter()
                .map(|snapshot| ChartPoint {
                    elapsed_secs: snapshot.elapsed_ms as f64 / 1000.0,
                    value: mapper(snapshot),
                })
                .collect(),
        }
    }
}

#[derive(Clone, Copy)]
enum AxisFormat {
    Rate,
    Millis,
}

fn summary_cards(cards: &[(&str, String)], x: f64, y: f64) -> String {
    let mut svg = String::from(r#"<g class="font">"#);
    for (index, (label, value)) in cards.iter().enumerate() {
        let col = index % 4;
        let row = index / 4;
        let card_x = x + col as f64 * 268.0;
        let card_y = y + row as f64 * 96.0;
        svg.push_str(&format!(
            r##"
<rect x="{card_x}" y="{card_y}" width="248" height="76" rx="8" fill="#ffffff" stroke="#d9e0ea"/>
<text x="{label_x}" y="{label_y}" class="muted" font-size="15" font-weight="750">{label}</text>
<text x="{value_x}" y="{value_y}" class="ink" font-size="26" font-weight="850">{value}</text>
"##,
            card_x = card_x,
            card_y = card_y,
            label_x = card_x + 16.0,
            label_y = card_y + 28.0,
            value_x = card_x + 16.0,
            value_y = card_y + 58.0,
            label = escape_xml(label),
            value = escape_xml(value)
        ));
    }
    svg.push_str("</g>");
    svg
}

fn chart_svg(
    title: &str,
    x: f64,
    y: f64,
    width: f64,
    height: f64,
    series: &[ChartSeries],
    format: AxisFormat,
    samples_label: &str,
    lang: ExportLang,
) -> String {
    let pad_left = 76.0;
    let pad_right = 30.0;
    let pad_top = 58.0;
    let pad_bottom = 70.0;
    let inner_x = x + pad_left;
    let inner_y = y + pad_top;
    let inner_w = width - pad_left - pad_right;
    let inner_h = height - pad_top - pad_bottom;
    let value_max = series
        .iter()
        .flat_map(|line| line.points.iter().map(|point| point.value))
        .fold(0.0_f64, f64::max);
    let max_value = nice_max(value_max, axis_floor(format));
    let elapsed_max = series
        .iter()
        .flat_map(|line| line.points.iter().map(|point| point.elapsed_secs))
        .fold(0.0_f64, f64::max);
    let x_max = nice_time_max(elapsed_max);

    let mut svg = format!(
        r##"<g class="font">
<rect x="{x}" y="{y}" width="{width}" height="{height}" rx="10" fill="#ffffff" stroke="#d9e0ea"/>
<text x="{title_x}" y="{title_y}" class="ink" font-size="22" font-weight="850">{title}</text>
"##,
        x = x,
        y = y,
        width = width,
        height = height,
        title_x = x + 24.0,
        title_y = y + 36.0,
        title = escape_xml(title)
    );

    let mut legend_x = x + width - 310.0;
    for line in series {
        svg.push_str(&format!(
            r##"<rect x="{lx}" y="{ly}" width="22" height="4" rx="2" fill="{color}"/>
<text x="{tx}" y="{ty}" class="muted" font-size="14">{label}</text>
"##,
            lx = legend_x,
            ly = y + 27.0,
            tx = legend_x + 30.0,
            ty = y + 34.0,
            color = line.color,
            label = escape_xml(line.label)
        ));
        legend_x += 96.0;
    }

    for tick in 0..=4 {
        let t = tick as f64 / 4.0;
        let gy = inner_y + inner_h * t;
        let value = max_value * (1.0 - t);
        svg.push_str(&format!(
            r##"<line x1="{inner_x}" y1="{gy}" x2="{x2}" y2="{gy}" stroke="#e6ebf2" stroke-width="1"/>
<text x="{label_x}" y="{label_y}" class="muted" font-size="13" text-anchor="end">{label}</text>
"##,
            inner_x = inner_x,
            gy = gy,
            x2 = inner_x + inner_w,
            label_x = inner_x - 10.0,
            label_y = gy + 4.0,
            label = escape_xml(&format_axis(value, format, lang))
        ));
    }

    for tick in 0..=6 {
        let t = tick as f64 / 6.0;
        let gx = inner_x + inner_w * t;
        let value = x_max * t;
        svg.push_str(&format!(
            r##"<line x1="{gx}" y1="{inner_y}" x2="{gx}" y2="{y2}" stroke="#edf2f7" stroke-width="1"/>
<text x="{gx}" y="{label_y}" class="muted" font-size="13" text-anchor="middle">{label}</text>
"##,
            gx = gx,
            inner_y = inner_y,
            y2 = inner_y + inner_h,
            label_y = inner_y + inner_h + 24.0,
            label = escape_xml(&format_seconds(value))
        ));
    }
    svg.push_str(&format!(
        r##"<text x="{unit_x}" y="{unit_y}" class="muted" font-size="13">s</text>
"##,
        unit_x = inner_x + inner_w + 20.0,
        unit_y = inner_y + inner_h + 24.0
    ));

    for line in series {
        if line.points.is_empty() {
            continue;
        }

        let points = line
            .points
            .iter()
            .map(|point| {
                let px = inner_x + inner_w * (point.elapsed_secs / x_max).clamp(0.0, 1.0);
                let py = inner_y + inner_h - ((point.value / max_value).clamp(0.0, 1.0) * inner_h);
                format!("{px:.2},{py:.2}")
            })
            .collect::<Vec<_>>()
            .join(" ");
        svg.push_str(&format!(
            r##"<polyline points="{points}" fill="none" stroke="{color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
"##,
            points = points,
            color = line.color
        ));
    }

    svg.push_str(&format!(
        r##"<text x="{footer_x}" y="{footer_y}" class="muted" font-size="13">{samples} {samples_label}</text>
</g>
"##,
        footer_x = inner_x,
        footer_y = y + height - 18.0,
        samples = series.first().map(|line| line.points.len()).unwrap_or(0),
        samples_label = escape_xml(samples_label)
    ));

    svg
}

fn nice_max(raw: f64, floor: f64) -> f64 {
    if raw <= 0.0 {
        return floor;
    }
    let pow = 10_f64.powf(raw.log10().floor());
    let scaled = raw / pow;
    let nice = if scaled <= 1.0 {
        1.0
    } else if scaled <= 2.0 {
        2.0
    } else if scaled <= 5.0 {
        5.0
    } else {
        10.0
    };
    (nice * pow).max(floor)
}

fn nice_time_max(raw_secs: f64) -> f64 {
    if raw_secs <= 10.0 {
        10.0
    } else if raw_secs <= 30.0 {
        30.0
    } else if raw_secs <= 60.0 {
        60.0
    } else {
        nice_max(raw_secs, 60.0)
    }
}

fn axis_floor(format: AxisFormat) -> f64 {
    match format {
        AxisFormat::Rate => 100.0,
        AxisFormat::Millis => 10.0,
    }
}

fn format_axis(value: f64, format: AxisFormat, lang: ExportLang) -> String {
    match format {
        AxisFormat::Rate => format_rate(value),
        AxisFormat::Millis => format_ms(value, lang),
    }
}

fn format_seconds(value: f64) -> String {
    if value >= 1000.0 {
        compact(value)
    } else if value >= 100.0 || (value.fract().abs() < 0.001) {
        format!("{value:.0}")
    } else if value >= 10.0 {
        format!("{value:.1}")
    } else {
        format!("{value:.2}")
    }
}

fn compact(value: f64) -> String {
    if value >= 1_000_000.0 {
        format!("{:.1}M", value / 1_000_000.0)
    } else if value >= 1_000.0 {
        format!("{:.1}K", value / 1_000.0)
    } else {
        format!("{:.0}", value)
    }
}

fn format_rate(value: f64) -> String {
    if value >= 1000.0 {
        compact(value)
    } else if value >= 100.0 {
        format!("{value:.0}")
    } else if value >= 10.0 {
        format!("{value:.1}")
    } else {
        format!("{value:.2}")
    }
}

fn format_ms(value: f64, lang: ExportLang) -> String {
    if value >= 1000.0 {
        if lang == ExportLang::Zh {
            format!("{:.2}秒", value / 1000.0)
        } else {
            format!("{:.2}s", value / 1000.0)
        }
    } else if value >= 10.0 {
        format!("{value:.1}ms")
    } else {
        format!("{value:.2}ms")
    }
}

fn format_duration(ms: u64, lang: ExportLang) -> String {
    let ms = ms as f64;
    if ms >= 3_600_000.0 {
        if lang == ExportLang::Zh {
            format!("{:.2}小时", ms / 3_600_000.0)
        } else {
            format!("{:.2}h", ms / 3_600_000.0)
        }
    } else if ms >= 60_000.0 {
        if lang == ExportLang::Zh {
            format!("{:.2}分钟", ms / 60_000.0)
        } else {
            format!("{:.2}min", ms / 60_000.0)
        }
    } else if ms >= 1000.0 {
        if lang == ExportLang::Zh {
            format!("{:.2}秒", ms / 1000.0)
        } else {
            format!("{:.2}s", ms / 1000.0)
        }
    } else {
        format!("{ms:.0}ms")
    }
}

fn mode_label(mode: &str, lang: ExportLang) -> String {
    match (lang, mode) {
        (ExportLang::Zh, "conn") => "连接".to_string(),
        (ExportLang::Zh, "sub") => "订阅".to_string(),
        (ExportLang::Zh, "pub") => "发布".to_string(),
        _ => mode.to_string(),
    }
}

fn status_label(status: &str, lang: ExportLang) -> String {
    match (lang, status) {
        (ExportLang::Zh, "idle") => "空闲".to_string(),
        (ExportLang::Zh, "starting") => "启动中".to_string(),
        (ExportLang::Zh, "running") => "运行中".to_string(),
        (ExportLang::Zh, "stopping") => "停止中".to_string(),
        (ExportLang::Zh, "completed") => "已完成".to_string(),
        (ExportLang::Zh, "stopped") => "已停止".to_string(),
        (ExportLang::Zh, "failed") => "失败".to_string(),
        _ => status.to_string(),
    }
}

fn escape_xml(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
